import "../globals.css";
import vazirFont from "@/constants/localFonts";
import Header from "@/app/Header";
import { Toaster } from "react-hot-toast";
import Providers from "@/app/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir={"rtl"} className={`${vazirFont.variable} font-sans`}>
      <body className={`${vazirFont.variable} font-sans`}>
        <Providers>
          <Toaster />
          <Header />
          <div className="container xl:max-w-screen-xl">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
